# Generated by Django 4.2.11 on 2024-04-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_students_file_remove_students_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='lastname',
        ),
    ]
