# Generated by Django 4.2.11 on 2024-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_nm_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nm',
            name='age',
            field=models.IntegerField(),
        ),
    ]
