# Generated by Django 4.2.11 on 2024-04-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_discussion', models.TextField()),
                ('book_image', models.ImageField(upload_to='book_images')),
            ],
        ),
    ]
