# Generated by Django 4.2.11 on 2024-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
